version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=pwd   # Elasticsearch 기본 패스워드
      - xpack.security.enabled=false #Enable HTTP request (for develop)
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./src/main/resources/elasticsearch/synonyms.txt:/usr/share/elasticsearch/config/analysis/synonyms.txt:ro
      - ./src/main/resources/elasticsearch/userdict.txt:/usr/share/elasticsearch/config/analysis/userdict.txt:ro

volumes:
  es_data: